image: "node:8.10.0"

cache:
  paths:
    - node_modules/

# Create the link so certain modules can be setup with node from inside npm
before_script:
  - npm install --registry=https://registry.npm.taobao.org

stages:
  - build
  - check

typecheck:
  stage: build
  script:
    - npm run build
  tags:
    - linux

checkstyle:
  stage: check
  script:
    - npm run checkstyle
  tags:
    - linux
